### ISSUE TITLE
Security design flaw by using /tmp

### ISSUE THREAD

**Issue by Mic92** [timbertson/runix#2]
`/tmp` comes with the permission 0666, which means that all users can write to it.
That means if one user on the system unpacks a binary to /tmp than another user can overwrite binaries and escalate privileges. At minimum the tool should check the owner of the directories it is trying to unpack and fail if it already exists.

**Comment by timbertson** [comment]
The files aren't actually extracted in /tmp, it's just a symlink. I don't know exactly what the rules are for overwriting files in /tmp, it may differ per distro. But I just tried both `rm ` and `ln -sfn` to mess with another user's symlink, and it was denied. Maybe it differs by distro, I'm pretty sure I've read about slightly different ownership rules for /tmp.

**Comment by timbertson** [comment]
Ah right, I think this means it should be fine, as long as your tmp has the standard permissions of `1777`: https://unix.stackexchange.com/questions/71622/what-are-correct-permissions-for-tmp-i-unintentionally-set-it-all-public-recu

**Comment by timbertson** [comment]
I'd avoid using this approach if I could, but it needs to use a base path that is no longer than `/nix/store`, and there aren't many candidates outside `/tmp`

**Comment by Mic92** [comment]
`$XDG_RUNTIME_DIR` is present on most linux distributions and points to a per-user /tmp.
MacOS also has a per user /tmp but you need to use $TMPDIR rather than hard-coding /tmp.
If you really need to use /tmp, you can do something like mkdir /tmp/runix-$(id -u) and fail execution if the directory already exists and is not owned by yourself.

**Comment by Mic92** [comment]
Ah. You actually cannot make the string longer... Well than it's flawed and shouldn't be used on multi-user systems.

**Comment by timbertson** [comment]
Closing this as a known issue. It's _secure_ in that others can't alter what you run (on systems with 1777 permissions on /tmp), but agree it's not functional for multi-user use.
